# coding: utf-8

"""
    Car Rental API

    API for managing car rentals

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.myapp_api import MyappApi


class TestMyappApi(unittest.TestCase):
    """MyappApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MyappApi()

    def tearDown(self) -> None:
        pass

    def test_create_car_list(self) -> None:
        """Test case for create_car_list

        """
        pass

    def test_create_rent_car(self) -> None:
        """Test case for create_rent_car

        """
        pass

    def test_create_return_car(self) -> None:
        """Test case for create_return_car

        """
        pass

    def test_destroy_car_detail(self) -> None:
        """Test case for destroy_car_detail

        """
        pass

    def test_destroycancel_rental(self) -> None:
        """Test case for destroycancel_rental

        """
        pass

    def test_list_cars(self) -> None:
        """Test case for list_cars

        """
        pass

    def test_listrental_lists(self) -> None:
        """Test case for listrental_lists

        """
        pass

    def test_retrieve_car_detail(self) -> None:
        """Test case for retrieve_car_detail

        """
        pass

    def test_update_car_detail(self) -> None:
        """Test case for update_car_detail

        """
        pass


if __name__ == '__main__':
    unittest.main()
