# Generated by Django 5.2.7 on 2025-10-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.car'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(),
        ),
    ]
